(let* ((inc (lambda (num succ zero) (succ (num succ zero))))
       (+ (lambda (num1 num2 succ zero) (num1 succ (num2 succ zero))))
       (* (lambda (num1 num2 succ zero) (num1 (num2 succ) zero)))
       (0 (lambda (succ zero) zero))
       (1 (inc 0))
       (2 (+ 1 1))
       (4 (* 2 2)))
  (* 4 4))
